# Generated by Django 5.2.15 on 2026-07-09 05:31

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100, validators=[apps.user.models.validate_timezone_name]),
        ),
    ]
