# Generated by Django 5.2.15 on 2026-07-09 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_minutely_checker_task(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Create crontab for * * * * * (every minute)
    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="*",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    # Create the minutely checker task
    PeriodicTask.objects.get_or_create(
        name="send-good-morning-emails-checker",
        defaults={
            "task": "apps.customer.tasks.send_good_morning_emails",
            "crontab": schedule,
            "enabled": True,
            "description": "Checks and sends Good Morning emails every minute based on timezone-specific configuration.",
        },
    )


def remove_minutely_checker_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="send-good-morning-emails-checker").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_created_at_customer_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email_type', models.CharField(max_length=50)),
                ('sent_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='customer.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'constraints': [models.UniqueConstraint(fields=('customer', 'email_type', 'sent_date'), name='unique_customer_email_type_date')],
            },
        ),
        migrations.RunPython(
            create_minutely_checker_task,
            remove_minutely_checker_task,
        ),
    ]
